apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    product: sagl
    app: cloud-api
  name: cloud-api
  namespace: xeonr-prod-sagl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        product: sagl
        app: cloud-api
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault-active.vault.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: kubernetes
        vault.security.banzaicloud.io/vault-role: sagl-prod-cloud-api
        vault.security.banzaicloud.io/enable-json: "true"
      name: cloud-api
    spec:
      serviceAccountName: vault-auth
      containers:
        - image: europe-west1-docker.pkg.dev/xeonr-io/sagl/cloud-api
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: production
            - name: SAGL_DISCORD_CLIENT_ID
              value: "vault:sagl/data/cloud-api/discord#clientId"
            - name: SAGL_DISCORD_CLIENT_SECRET
              value: "vault:sagl/data/cloud-api/s3#clientSecret"
            - name: SAGL_MYSQL_DATABASE
              value: "sagl-cloud"
            - name: SAGL_MYSQL_USERNAME
              value: "vault:sagl/data/database/mysql#username"
            - name: SAGL_MYSQL_PASSWORD
              value: "vault:sagl/data/database/mysql#password"
            - name: SAGL_MYSQL_HOST
              value: "vault:sagl/data/database/mysql#host"
            - name: SAGL_REDIS_HOST
              value: "vault:sagl/data/database/redis#host"
            - name: SAGL_REDIS_PORT
              value: "vault:sagl/data/database/redis#port"
            - name: SAGL_REDIS_PASSWORD
              value: "vault:sagl/data/database/redis#password"
            - name: SAGL_STORAGE_JSON
              value: "vault:sagl/data/cloud-api/gcs#gcsJson"
            - name: SAGL_JWT_SECRET
              value: "vault:sagl/data/cloud-api/jwt#secret"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          name: cloud-api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: cloud-api
  name: cloud-api
  namespace: xeonr-prod-sagl
spec:
  type: ClusterIP
  selector:
    app: cloud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cloud-api
  namespace: xeonr-prod-sagl
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cloud-api.sagl.app`)
      priority: 10
      services:
        - name: cloud-api
          port: 80
